development:
  secret_key_base: 41d6e2ce903b34997165390c83f436e9e11580da0db6e1dce3dd6b917a94bb04cb1aad3656f7b1630781955c462dd7c8bde254644dd01f12947087d1ae0cad79
test:
  secret_key_base: fd53fd121b20833b8124314c7191eb6811c51413557afdb200cc56ec6eb2e6d0be28b6371e5f1765a49340946a82cde7bc78d7094fae003dbc41672320b6a97f
  